# Site settings
title: Zachary Tieu
email: tieu.zachary@gmail.com
description: > # keep this and put description below
  Technical Designer and Programmer
url: "https://zacharytieu.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/ztieu"

# Build settings
markdown: kramdown
permalink: pretty
