# Site settings
title: Zachary Tieu
email: tieu.zachary@gmail.com
description: > # keep this and put description below
  Technical Designer and Programmer, graduating from USC this year! Passionate about designing and implementing mechanics that make the stories within and born from games sing.
  Favorite Game Genre: Turn-Based Strategy
  Favorite Game: Harebrained Studio’s Shadowrun
url: "https://ZacharyTieu.github.io" # the base hostname & protocol for your site
linkedin_url: "www.linkedin.com/in/ztieu"
github_username: ZachTier
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
